### ISSUE TITLE
Feature: Display variables in different formats 

### ISSUE THREAD

**Issue by sbixl** [iarsystems/iar-vsc-debug#13]
It would be very nice, if the contents of a variable in the variables view can be displayed in different formats (hex dec, bin,...). The Cortex-Debug [1] plugin has a nice feature to solve this by showing a tooltip while hovering of the accordant variable:

![129586732-71228fee-6d6c-4993-ac8f-c9ca93b7772f](https://user-images.githubusercontent.com/32767146/189412522-7660fd79-6ea6-41f5-b77a-1d2709bf96b4.png)

[1]  https://marketplace.visualstudio.com/items?itemName=marus25.cortex-debug

**Comment by HampusAdolfsson** [comment]
This is something we definitely want to support and are looking into. One option would be to add a right click option to each variable that lets you set its display format, or we could add some global setting that changes the display format for all variables.

Due to how our debugger API is shaped, we can't show all formats at the same time like Cortex-Debug without affecting performance too much.

**Comment by davidanderle** [comment]
I think GDB-based debuggers use [Output formats](https://ftp.gnu.org/old-gnu/Manuals/gdb/html_node/gdb_54.html) to do this. Essentially, you could add your variable as
`myVar, h`
in the watch window to display it as a hexadecimal value. Is this something that would be easier to implement?

**Comment by HampusAdolfsson** [comment]
That would work, but a right-click option on the variables would probably be more intuitive and not much more work to implement.

**Comment by HampusAdolfsson** [comment]
The `1.40.1` release adds a new "Format" option when right clicking variables, similar to the Embedded Workbench IDE:
![image](https://github.com/user-attachments/assets/766b95d5-5e69-4fde-b71f-2699f87718bf)
